volumes:
  mongodb-data:

services:
  fdm-monster:
    container_name: fdm-monster
    image: davidzwa/fdm-monster:development
    restart: always
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    ports:
      - 4001:4000
    environment:
      - MONGO=mongodb://host.docker.internal:27017/fdm-monster?readPreference=primary&ssl=false
    volumes:
      # Volumes as local relative folders (validate with 'docker-compose config')
      - ./fdm-monster/logs:/app/logs
      - ./fdm-monster/scripts:/app/scripts
      - ./fdm-monster/images:/app/images
