volumes:
  mongodb-data:

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: fdm-monster
    ports:
      # default is 27017
      - "21111:27017"
    volumes:
      - ./fdm-monster/mongodb-data:/data/db
    restart: unless-stopped

  fdm-monster:
    container_name: fdm-monster
    image: davidzwa/fdm-monster:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - MONGO=mongodb://mongodb:27017/fdm-monster?readPreference=primary&ssl=false
      - NODE_ENV=development
      - SERVER_PORT=4000
    volumes:
      - ./fdm-monster/media/:/app/media
