volumes:
  mongodb-data:

# For more detailed info, read /docs/USING_DOCKER.md
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: fdm-monster
    ports:
      # default is 27017
      - "21111:27017"
    volumes:
      - ./fdm-monster/mongodb-data:/data/db
    restart: unless-stopped

  fdm-monster:
    container_name: fdm-monster
    image: davidzwa/fdm-monster:v1.2.0-rc2
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    ports:
      - "4001:4000"
    environment:
      - MONGO=mongodb://mongodb:21111/fdm-monster?readPreference=primary&ssl=false
    volumes:
      # Volumes as local relative folders (validate with 'docker-compose config')
      - ./fdm-monster/logs:/app/logs
      - ./fdm-monster/file-storage:/app/file-storage
      - ./fdm-monster/scripts:/app/scripts
      - ./fdm-monster/images:/app/images
