volumes:
  mongodb-data:

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      # MongoDB with authentication (optional)
#      - MONGO_INITDB_ROOT_USERNAME=YOUR_ROOT_NAME
#      - MONGO_INITDB_ROOT_PASSWORD=YOUR_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=fdm-monster
    ports:
      - "21111:27017"
    volumes:
      - ./fdm-monster/mongodb-data:/data/db
      - ./fdm-monster/mongoconfig:/data/configdb
    restart: unless-stopped

  fdm-monster:
    container_name: fdm-monster
    image: davidzwa/fdm-monster:latest
    build:
      context: ./server
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
#      - MONGO=mongodb://<username>:<password>@mongodb:27017/fdm-monster?authSource=admin
      - MONGO=mongodb://mongodb:27017/fdm-monster?readPreference=primary&ssl=false
      - NODE_ENV=development
      - SERVER_PORT=4000
    volumes:
      - ./fdm-monster/media/:/media
