volumes:
  mongodb-data:

# For more detailed info, read /docs/USING_DOCKER.md
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: fdm-monster
    ports:
      # default is 27017
      - "21111:27017"
    volumes:
      - ./fdm-monster/mongodb-data:/data/db
    restart: unless-stopped

  fdm-monster:
    container_name: fdm-monster
    image: davidzwa/fdm-monster:v1.3.0-rc4
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    ports:
      - "4001:5001"
    environment:
      - MONGO=mongodb://mongodb:27017/fdm-monster?readPreference=primary&ssl=false
      - NODE_ENV=development
      - SERVER_PORT=5001
    volumes:
      - ./fdm-monster/media/:/app/media
