---
- name: Test
  hosts: all
  become: no
  vars_files:
    - vars/main.yml
  tasks:
    - name: Set bash interactive profile command
      set_fact:
        bash: "bash -ic"
        # src_nvm: ". {{ ansible_env.HOME }}/.nvm/nvm.sh"
    
    - name: "Check nvm {{ node_version }}"
      become: no
      shell: "{{bash}} 'nvm -v'"
      register: nvm_version_response
      failed_when: nvm_version not in nvm_version_response.stdout
      changed_when: nvm_version_response.rc != 0

    - name: "Check node {{ node_version }}"
      become: no
      shell: "{{bash}} 'node -v'"
      register: node_version_response
      failed_when: node_version not in node_version_response.stdout
      changed_when: node_version_response.rc != 0
    
    - name: "Check yarn v1"
      become: no
      shell: "{{bash}} 'yarn -v'"
      register: yarn_version_response
      failed_when: yarn_version_response.stdout is version('2', '>=')
      changed_when: yarn_version_response.rc != 0      