services:
  # States MQTT plugin incompatible
  octoprint:
    image: davidzwa/octoprint:1.8.7
    container_name: op0
    privileged: true
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /dev/:/dev/
      - ./op0:/octoprint
  # MQTT plugin works
  octoprint2:
    image: octoprint/octoprint:1.9.3
    container_name: op1
    privileged: true
    restart: unless-stopped
    ports:
      - 81:80
    volumes:
      - /dev/:/dev/
      - ./op1:/octoprint
