services:
  # States MQTT plugin incompatible
  octoprint:
    image: octoprint/octoprint:latest
    container_name: op0
    privileged: true
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /dev/:/dev/
      - ./op0:/octoprint
  # MQTT plugin works
  octoprint2:
    image: octoprint/octoprint:1.10.3
    container_name: op1
    privileged: true
    restart: unless-stopped
    ports:
      - 81:80
    volumes:
      - /dev/:/dev/
      - ./op1:/octoprint
  octoprint3:
    image: octoprint/octoprint:1.10.3
    container_name: op2
    privileged: true
    restart: unless-stopped
    ports:
      - 82:80
    volumes:
      - /dev/:/dev/
      - ./op2:/octoprint
