services:
  octoprint:
    build:
      context: ./default1.9.0
      dockerfile: octoprint.Dockerfile
    # image: 127.0.0.1:5000/octoprint-virtual:latest
    image: octoprint/octoprint-virtual:1.9.0
    # scale up to 5
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    ports:
      - 80
