version: "3"
services:
  mainsail:
    image: ghcr.io/mainsail-crew/mainsail
    container_name: mainsail
    ports:
      - "8081:80"
    volumes:
      - "./mainsail/config.json:/usr/share/nginx/html/config.json"
