name: Docker multi-arch release
on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
      - 'develop'
jobs:
  docker:
    runs-on: ubuntu-latest
    name: "Docker build"
    steps:
      - name: "Decide tags to use"
        run: |
          if ${{ github.ref == 'refs/heads/main' }} == true; then
            echo 'TAG_EDGE=latest' >> $GITHUB_ENV
          elif ${{ github.ref == 'refs/heads/develop' }} == true; then
            echo 'TAG_EDGE=develop' >> $GITHUB_ENV
          else
            echo 'TAG_EDGE=edge' >> $GITHUB_ENV
          fi
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4
        with:
          images: davidzwa/fdm-monster
          # x.y.z versioning (not strictly 'vx.y.z' semver)
          tag-match: ^(\d+\.)?(\d+\.)?(\*|\d+)$
          tag-custom: |
            ${{env.TAG_EDGE}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashfiles('./docker/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Show docker tags"
        run: |
          echo '${{ steps.docker_meta.outputs.tags }}'
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:server"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
