name: Node.js CI MongoDB

on:
  pull_request:
  workflow_dispatch:
  # Runs from default branch, which is develop
  schedule:
    - cron: '0 0 * * *'
jobs:
  nodejs-build-mongodb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - run: yarn set version berry
      - run: yarn install --immutable
      - run: yarn run build
      # non-coverage sqlite tests
      - run: yarn run test:mongodb
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
