name: Frontend Webpack and NPM Publish
on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'development'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci --no-optional
        working-directory: client-vue
      - run: npm build
        working-directory: client-vue
      - run: npm run build
        working-directory: client-vue
      - uses: JS-DevTools/npm-publish@v1
        if: ${{ github.repository.name == '3d-print-farm' }}
        with:
          dry-run: false
          token: ${{ secrets.NPM_TOKEN }}
          package: client-vue/package.json
