name: Vue publish
on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'develop'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: yarn install --immutable --immutable-cache --check-cache
        working-directory: client-vue
      - run: yarn run build
        working-directory: client-vue
      - uses: JS-DevTools/npm-publish@v1
        if: ${{ github.repository.name == 'fdm-monster' }}
        with:
          dry-run: true
          token: ${{ secrets.NPM_TOKEN }}
          package: client-vue/package.json
